#!/bin/bash

set -eo pipefail

if [ "$#" -eq 1 ]; then
	DRAFT="$(date +%Y-%m-%d)-$1.md"
	#
	cd "$SB/creativity/drafts" || exit 1
	if [ ! -f "$DRAFT" ]; then
		touch "$DRAFT"
		# echo "created $DRAFT"
	fi
	nvim "$DRAFT"
else
	echo "this function requires one argument"
	echo "usage: mkdraft name"
fi

exit 0
