#!/bin/bash

set -eo pipefail

if [ "$#" -eq 1 ]; then
	SITE="$1"
	#
	cd ~/repo/ejsdotsh/web
	if [ ! -d "$SITE" ]; then
		echo "creating site"
		hugo new site "$SITE"
		cd "$SITE"
		git init .
		hugo mod init github.com/ejsdotsh/$SITE
	else
		echo "that directory already exists"
	fi
else
	echo "this function requires one argument"
	echo "usage: mksite site.name"
fi

exit 0
