#!/bin/bash

set -eo pipefail

# upgrade all the python3 modules in the current venv
# make sure we are at the root of the venv
if [ ! -f .venv/bin/python3 ]; then
	echo "make sure you are at the root of the venv"
else
	# upgrade pip
	.venv/bin/python3 -m pip install -U pip
	# upgrade the rest of the modules
	.venv/bin/python3 -m pip freeze | awk -F'==' '{print $1}' | xargs .venv/bin/python3 -m pip install -U
fi

exit 0
