#!/bin/bash

# wayland stuff
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_TYPE=wayland
# export CLUTTER_BACKEND=wayland

export GDK_BACKEND=wayland
export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia
# export __GL_GSYNC_ALLOWED=0
# export __GL_VRR_ALLOWED=0

export SDL_VIDEODRIVER=wayland

export QT_QPA_PLATFORM=wayland
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

export _JAVA_AWT_WM_NONREPARENTING=1

# export WLR_DRM_NO_ATOMIC=1
# export WLR_NO_HARDWARE_CURSORS=1

export MOZ_ENABLE_WAYLAND=1
# export MOZ_WEBRENDER=1
# export MOZ_ACCELERATED=1

# using systemd and want sway output to go to the journal
exec systemd-cat --identifier=sway sway --unsupported-gpu $@

