#!/bin/bash

set -eo pipefail

# add colors to `go test`
# TODO update colors to match shell colors
go test $* |
	sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' |
	sed ''/SKIP/s//$(printf "\033[34mSKIP\033[0m")/'' |
	sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/'' |
	sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/'' |
	GREP_COLOR="01;33" egrep --color=always '\s*[a-zA-Z0-9\-_.]+[:][0-9]+[:]|^'

exit 0
