#!/usr/bin/env bash

# if nvim exists
if type nvim >/dev/null 2>&1; then
	alias vim='nvim'
	alias vi='nvim'
fi

# aliases
alias ls='ls --color'
alias mkpy='python3 -m venv .venv && .venv/bin/python3 -m pip install -U pip setuptools wheel black mypy'
alias mkgomod='go mod init github.com/ejsdotsh/$(basename $(pwd))'
alias rebash='source ~/.bashrc'
alias unbrewall='brew uninstall --formula $(brew list)'
alias terraform='tofu'
